[package]
name = "horsenuggets/t"
description = "A Runtime Typechecker for Roblox"
version = "3.1.1-horse.0.3"
license = "MIT"
authors = ["Osyris"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["*"]
include = ["lib", "lib/init.lua", "default.project.json", "LICENSE", "README.md", "wally.toml", ".luaurc", "init.luau"]

[dependencies]
